services:
  zerotier:
    build: .
    container_name: zerotier
    devices:
      - /dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    environment:
      - ZEROTIER_NETWORK_ID=${ZEROTIER_NETWORK_ID}
      - ZEROTIER_CENTRAL_TOKEN=${ZEROTIER_CENTRAL_TOKEN}
    restart: unless-stopped
